package com.s2s.mobile.pipeline

/**
 * A device capability the assistant may invoke — set a timer, toggle the torch,
 * read the battery. Ported from the C++ `tool_registry.h` contract.
 */
/**
 * Type/required/enum metadata for one tool parameter — richer than a bare
 * description, but still flat: no nested objects, since small on-device
 * models follow one flat JSON call shape far more reliably than the nested
 * OpenAI tool schema (see `ToolRegistry`'s class doc, in the `s2s-tools`
 * plugin repo — this contract is deliberately shaped around that reality
 * even though core has no dispatcher implementation of its own).
 */
data class ToolParameter(
    val description: String,
    /** JSON Schema primitive type name: "string", "number", "boolean", "integer". */
    val type: String = "string",
    val required: Boolean = true,
    /** Restricts the value to one of these, if non-empty. */
    val enum: List<String> = emptyList(),
)

data class ToolDefinition(
    val name: String,
    val description: String,
    /**
     * Parameter name to human description. Kept flat; voice commands rarely
     * nest. Superseded by [schema] when that is non-empty — kept as the
     * simple path for a tool that has no real type/required/enum story.
     */
    val parameters: Map<String, String> = emptyMap(),
    /** Richer per-parameter type/required/enum metadata. See [ToolParameter]. */
    val schema: Map<String, ToolParameter> = emptyMap(),
)

/** A parsed request from the model to run a tool. */
data class ToolCall(val name: String, val arguments: Map<String, String>)

/** Outcome of a tool call, fed back to the model as context for its spoken reply. */
data class ToolResult(val name: String, val output: String, val isError: Boolean = false)

/**
 * Identity of one tool invocation, engine-generated and passed down to every
 * [ToolFunction] call — never generated by a tool itself.
 *
 * Exists so a stateful tool (open a page, then click on it, then read it) can
 * tell which calls belong to the same conversation without inventing its own
 * session mechanism. Deliberately minimal: no history, no Android [android.content.Context],
 * no network client — anything a tool needs beyond correlating its own calls
 * belongs to the tool's own construction, not here.
 */
data class ToolContext(
    /** The ongoing S2S conversation. Stable for the life of one [com.s2s.mobile.S2SEngine] session. */
    val sessionId: String,
    /** One user/model turn within [sessionId]. Shared by every tool call inside that turn. */
    val turnId: String,
    /** One specific tool invocation. Unique even across calls in the same turn. */
    val callId: String,
)

/** Implementation of a single tool. Runs on a worker thread; keep it quick. */
fun interface ToolFunction {
    operator fun invoke(context: ToolContext, arguments: Map<String, String>): String
}

/**
 * Registry of callable tools.
 *
 * The model is told what exists via [promptSection], and its output is scanned
 * by [parse]. Keeping both here means the prompt format and the parser cannot
 * drift apart.
 */
interface Tools {
    val definitions: List<ToolDefinition>

    fun register(definition: ToolDefinition, function: ToolFunction)

    fun unregister(name: String)

    /** System-prompt fragment describing the available tools, or null if none. */
    fun promptSection(): String?

    /** Extracts a tool call from model output, or null if it is plain speech. */
    fun parse(text: String): ToolCall?

    /**
     * Runs the tool call and blocks until it returns. Called on the engine's
     * LLM worker thread — a slow implementation (a network call, a page
     * render) delays that turn but does not block the mic or playback thread.
     * There is no cancellation signal today: a tool that can run long should
     * enforce its own timeout internally.
     */
    fun execute(call: ToolCall, context: ToolContext): ToolResult
}

/**
 * The "no tools registered" case — a contract-layer default, not a real
 * dispatcher. A host that wants actual tool calling supplies its own [Tools]
 * (e.g. `ToolRegistry`, or a plugin's own implementation); core never picks
 * one on the host's behalf.
 */
object NoopTools : Tools {
    override val definitions: List<ToolDefinition> = emptyList()
    override fun register(definition: ToolDefinition, function: ToolFunction) =
        throw UnsupportedOperationException("NoopTools cannot register tools — supply a real Tools implementation")
    override fun unregister(name: String) = Unit
    override fun promptSection(): String? = null
    override fun parse(text: String): ToolCall? = null
    override fun execute(call: ToolCall, context: ToolContext): ToolResult =
        ToolResult(call.name, "No tools registered", isError = true)
}
